[project]
name = "tgbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.21.0",
    "py3xui>=0.5.1",
    "pydantic>=2.11.7",
    "ruff>=0.12.12",
    "uuid>=1.30",
]
